### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by ivklgn** [Anton763/lab#1]
комментарий коммита должен отражать суть изменений, лучше разбивать задачу на подзадачу и чаще фиксировать изменения
https://github.com/lulldev/webdev/blob/master/coding-convections/git.md

**Comment by ivklgn** [comment]
лучше использовать договоренность из соглашения о форматирования - 2 пробельных символа в отступах + автоформатирование

**Comment by ivklgn** [comment]
`bg_white`, `product-info` - нужно определится со стилем именования.

**Comment by ivklgn** [comment]
patch.css - имя не отражает назначения стилей

**Comment by ivklgn** [comment]
```
.btn-custom{
	color: rgba(0,0,0,.3);
	text-decoration: underline;
}
```

```css
h1,h2,h3,h4,h5,h6{
	font-family: 'Work Sans', sans-serif;
	color: #000000;
	margin-top: 0;
	font-weight: 400;
}
```

поправить форматирование фигурных скобок, запятых
